### PR TITLE
Iris shaders 1.16.x/iris

### PR DESCRIPTION
**Pull request by nullified33**

### CODE REVIEW

**Comment by 3prm3** [comment]
An experimental fix

**Comment by 3prm3** [comment]
not a fix really

**Comment by nullified33** [comment]
just a base

**Comment by nullified33** [comment]
* What went wrong:
A problem occurred configuring root project 'sodium-fabric-compat_next_1_16_4'.
> Could not resolve all files for configuration ':modCompileClasspath'.
   > Could not find net.coderbot.iris:iris:0.3.0-sodium_compatibility.
     Searched in the following locations:
       - file:/C:/Users/Clement/.m2/repository/net/coderbot/iris/iris/0.3.0-sodium_compatibility/iris-0.3.0-sodium_compatibility.pom
       - https://jitpack.io/net/coderbot/iris/iris/0.3.0-sodium_compatibility/iris-0.3.0-sodium_compatibility.pom
       - file:/C:/Users/Clement/Downloads/sodium-fabric-compat_next_1_16_4/build/loom-cache/iris-0.3.0-sodium_compatibility.jar
       - file:/C:/Users/Clement/Downloads/sodium-fabric-compat_next_1_16_4/build/loom-cache/iris.jar
       - file:/C:/Users/Clement/Downloads/sodium-fabric-compat_next_1_16_4/.gradle/loom-cache/remapped_mods/net/coderbot/iris/iris/0.3.0-sodium_compatibility/iris-0.3.0-sodium_compatibility.pom
       - https://maven.fabricmc.net/net/coderbot/iris/iris/0.3.0-sodium_compatibility/iris-0.3.0-sodium_compatibility.pom
       - https://libraries.minecraft.net/net/coderbot/iris/iris/0.3.0-sodium_compatibility/iris-0.3.0-sodium_compatibility.pom
       - https://repo.maven.apache.org/maven2/net/coderbot/iris/iris/0.3.0-sodium_compatibility/iris-0.3.0-sodium_compatibility.pom
       - file:/C:/Users/Clement/Downloads/sodium-fabric-compat_next_1_16_4/.gradle/loom-cache/1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2/iris-0.3.0-sodium_compatibility.jar
       - file:/C:/Users/Clement/Downloads/sodium-fabric-compat_next_1_16_4/.gradle/loom-cache/1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2/iris.jar
     Required by:
         project :

**Comment by nullified33** [comment]
If this error is fixed it will work

**Comment by machinesmith42** [comment]
@3prm3 we need to get iris and immersive compat first

**Comment by nullified33** [comment]
> @3prm3 we need to get iris and immersive compat first

ok

**Comment by nullified33** [comment]
> @3prm3 we need to get iris and immersive compat first

I have successfully merged the two

**Comment by nullified33** [comment]
https://github.com/3prm3/sodium-fabric/pull/6
I actually was able to merge the two

**Comment by machinesmith42** [comment]
Closing until updates

**Pull request closed without merging**
